# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setting the npm user
      #   run: npm adduser 

      - name: List files 1
        run: |
          echo '/home/runner/work/irrigai-background-public'
          ls -a /home/runner/work/irrigai-background-public
          echo '/home/runner/work/irrigai-background-public/irrigai-background-public'
          ls -a /home/runner/work/irrigai-background-public/irrigai-background-public


      - name: List current dir
        run: ls -a ./

      # - name: Checking npm authentication
      #   run: npm whoami --user-config ./.npmrc
      #   env:
      #     env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules # 👈 path for node_modules folder
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          # 👆 name of the chache key includes package-lock.json
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if:
          steps.cache-nodemodules.outputs.cache-hit != 'true'
          # 👆 if cache hits the skip this step.
        run: npm ci
     

      - name: List files 2
        run: |
          echo '/home/runner/work/irrigai-background-public'
          ls -a /home/runner/work/irrigai-background-public
          echo '/home/runner/work/irrigai-background-public/irrigai-background-public'
          ls -a /home/runner/work/irrigai-background-public/irrigai-background-public
          echo '/home/runner/work/irrigai-background-public/irrigai-background-public/release-public'
          ls -a /home/runner/work/irrigai-background-public/irrigai-background-public/release-public


      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACTION }}
          NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
